-- Generated by nwg-displays on 2026-09-17 at 07:45:00. Do not edit manually.

hl.monitor({
    output = "HDMI-A-1",
    mode = "2560x1440@59.95",
    position = "0x0",
    scale = 1.0,
    vrr = 0
})
hl.monitor({
    output = "DP-2",
    mode = "1920x1080@60.0",
    position = "2560x0",
    scale = 1,
    vrr = 0,
    transform = 1
})
