-- Generated by nwg-displays on 2026-09-17 at 07:44:50. Do not edit manually.

hl.workspace_rule({
  workspace = "1",
  monitor = "HDMI-A-1",
  default = true,
  persistent = true,
  default_name = "web"
})
hl.workspace_rule({
  workspace = "2",
  monitor = "HDMI-A-1",
  persistent = true,
  default_name = "code"
})
hl.workspace_rule({
  workspace = "3",
  monitor = "HDMI-A-1",
  persistent = true,
  default_name = "chat"
})
hl.workspace_rule({
  workspace = "4",
  monitor = "HDMI-A-1",
  persistent = true,
  default_name = "game"
})
hl.workspace_rule({
  workspace = "5",
  monitor = "HDMI-A-1",
  persistent = true,
  default_name = "japanese"
})
hl.workspace_rule({
  workspace = "6",
  monitor = "DP-2",
  default = true,
  persistent = true
})
hl.workspace_rule({
  workspace = "7",
  monitor = "DP-2",
  persistent = true
})
hl.workspace_rule({
  workspace = "8",
  monitor = "DP-2",
  persistent = true
})
hl.workspace_rule({
  workspace = "9",
  monitor = "DP-2",
  persistent = true
})
hl.workspace_rule({
  workspace = "10",
  monitor = "DP-2",
  persistent = true
})
